from point_tg import *

dictionary = {
PointTg(6,-4,-2):[['B', 'A', 'B']],
PointTg(3,-4,1):[['C', 'A', 'B']],
PointTg(0,2,-2):[['E', 'A', 'B']],
PointTg(3,2,-5):[['F', 'A', 'B']],
PointTg(4,-3,-1):[['A', 'C', 'B']],
PointTg(4,-6,2):[['B', 'C', 'B']],
PointTg(-2,-3,5):[['D', 'C', 'B']],
PointTg(-2,0,2):[['C', 'E', 'F'], ['E', 'C', 'B']],
PointTg(2,-4,2):[['B', 'C', 'E'], ['B', 'D', 'B'], ['C', 'A', 'C'], ['C', 'B', 'F']],
PointTg(-1,-4,5):[['C', 'D', 'B']],
PointTg(-4,2,2):[['E', 'C', 'E'], ['E', 'D', 'B']],
PointTg(-1,2,-1):[['E', 'A', 'C'], ['F', 'D', 'B']],
PointTg(4,1,-5):[['A', 'F', 'B']],
PointTg(4,-2,-2):[['B', 'A', 'E'], ['B', 'F', 'B']],
PointTg(-2,1,1):[['D', 'F', 'B']],
PointTg(-2,4,-2):[['E', 'A', 'E'], ['E', 'F', 'B'], ['F', 'D', 'F'], ['F', 'E', 'C']],
PointTg(5,-4,-1):[['B', 'A', 'C']],
PointTg(2,2,-4):[['F', 'A', 'C'], ['F', 'B', 'F']],
PointTg(5,-3,-2):[['A', 'B', 'C']],
PointTg(2,-6,4):[['C', 'B', 'C']],
PointTg(-1,-3,4):[['D', 'B', 'C']],
PointTg(2,0,-2):[['B', 'F', 'E'], ['F', 'B', 'C']],
PointTg(1,-4,3):[['B', 'D', 'C']],
PointTg(-2,-4,6):[['C', 'D', 'C']],
PointTg(-5,2,3):[['E', 'D', 'C']],
PointTg(-2,2,0):[['F', 'D', 'C']],
PointTg(1,1,-2):[['A', 'E', 'C']],
PointTg(-2,-2,4):[['C', 'D', 'F'], ['C', 'E', 'C']],
PointTg(-5,1,4):[['D', 'E', 'C']],
PointTg(1,-2,1):[['B', 'D', 'F'], ['C', 'A', 'E']],
PointTg(1,4,-5):[['F', 'A', 'E']],
PointTg(2,-1,-1):[['A', 'C', 'E']],
PointTg(-4,-1,5):[['D', 'C', 'E']],
PointTg(0,-2,2):[['B', 'D', 'E']],
PointTg(-3,-2,5):[['C', 'D', 'E']],
PointTg(-6,4,2):[['E', 'D', 'E']],
PointTg(-3,4,-1):[['F', 'D', 'E']],
PointTg(2,3,-5):[['A', 'F', 'E']],
PointTg(-4,3,1):[['D', 'F', 'E']],
PointTg(-4,6,-2):[['E', 'F', 'E']],
PointTg(5,-2,-3):[['B', 'A', 'F']],
PointTg(2,-2,0):[['C', 'A', 'F']],
PointTg(-1,4,-3):[['E', 'A', 'F']],
PointTg(2,4,-6):[['F', 'A', 'F']],
PointTg(5,-1,-4):[['A', 'B', 'F']],
PointTg(-1,-1,2):[['D', 'B', 'F']],
PointTg(-5,4,1):[['E', 'D', 'F']],
PointTg(1,3,-4):[['A', 'E', 'F']],
PointTg(-5,3,2):[['D', 'E', 'F']],
PointTg(-2,6,-4):[['F', 'E', 'F']]}

print(len(dictionary.keys()))
